// import inlineImage from "./inlineImage";

export { default as attachment } from "./attachment";
// export { default as file } from "./attachment";
export { default as acessibleImage } from "./accessibleImage";
export { default as accessibleVideo } from "./accessibleVideo";
export { default as blockContent } from "./blockContent";
export { default as blockText } from "./blockText";
export { default as captionedImage } from "./captionedImage";
export { default as classSetting } from "./classSetting";
export { default as eventCalendar } from "./eventCalendar";
export { default as faqItem } from "./faqItem";
export { default as faqs } from "./faqs";
export { default as imageSection } from "./imageSection";
export { default as inlineImage } from "./inlineImage";
export { default as muxVideo } from "./muxVideo";
export { default as navItem } from "./navItem";
export { default as seo } from "./seo";
export { default as simpleBlock } from "./simpleBlock";
export { default as social } from "./social";
export { default as textSection } from "./textSection";
